// <auto-generated />
using System;
using DataAgregatorWeb.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAgregatorWeb.Migrations
{
    [DbContext(typeof(PassFlowDBContext))]
    [Migration("20231211133714_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAgregatorWeb.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("bus_pkey");

                    b.ToTable("bus", (string)null);
                });

            modelBuilder.Entity("DataAgregatorWeb.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusCount")
                        .HasColumnType("integer");

                    b.Property<int>("BusId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("FeelsLike")
                        .HasColumnType("double precision");

                    b.Property<int>("Holiday")
                        .HasColumnType("integer");

                    b.Property<float>("Humidity")
                        .HasColumnType("real");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("boolean");

                    b.Property<int>("Join")
                        .HasColumnType("integer");

                    b.Property<int>("Left")
                        .HasColumnType("integer");

                    b.Property<double>("Precipitation")
                        .HasColumnType("double precision");

                    b.Property<float>("Pressure")
                        .HasColumnType("real");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("TrafficJams")
                        .HasColumnType("integer");

                    b.Property<int>("WayId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.Property<double>("Wind")
                        .HasColumnType("double precision");

                    b.HasKey("Id")
                        .HasName("trip_pkey");

                    b.HasIndex("BusId");

                    b.HasIndex("WayId");

                    b.ToTable("trip", (string)null);
                });

            modelBuilder.Entity("DataAgregatorWeb.Models.Way", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("way_pkey");

                    b.HasIndex(new[] { "Name" }, "name_unique")
                        .IsUnique();

                    b.ToTable("way", (string)null);
                });

            modelBuilder.Entity("DataAgregatorWeb.Models.Trip", b =>
                {
                    b.HasOne("DataAgregatorWeb.Models.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("trip_bus_fkey");

                    b.HasOne("DataAgregatorWeb.Models.Way", "Way")
                        .WithMany("Trips")
                        .HasForeignKey("WayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("trip_way_fkey");

                    b.Navigation("Bus");

                    b.Navigation("Way");
                });

            modelBuilder.Entity("DataAgregatorWeb.Models.Bus", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("DataAgregatorWeb.Models.Way", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
